server:
  port: 8761

eureka:
    client:
        # server should not register with itself as a server (client)
      register-with-eureka: false
        # prevent fetching its own service list
      fetch-registry: false